# prerequisites: run 'ansible-galaxy install -r requirements.yml'
# get ext roles:
#   https://github.com/mablanco/ansible-antirootkits.git
#   https://github.com/geerlingguy/ansible-role-clamav.git


- name: rkhunter - whitelisted processes
  ansible.builtin.lineinfile:
    path: "/etc/rkhunter.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - regexp: "(^|^#)ALLOWIPCPROC="
      line: "ALLOWIPCPROC=/usr/bin/gnome-shell"
  tags:
    - antirootkits

- name: clamav - configure freshclam for local signatue caching 1/2
  ansible.builtin.replace:
    path: /etc/clamav/freshclam.conf
    regexp: "(^{{ item }}.*)"
    ansible.builtin.replace: '#\1'
  with_items:
    - "DatabaseMirror"
  when: clamav_offlinedb
  tags:
    - clamav

- name: clamav - configure freshclam for local signatue caching 2/2
  ansible.builtin.lineinfile:
    path: /etc/clamav/freshclam.conf
    regexp: "(^{{ item.var }})(.*)$"
    line: "{{ item.var }} {{ item.value }}"
    state: present
  with_items:
    - var: "PrivateMirror"
      value: "{{ clamav_localcache }}"
    - var: "ScriptedUpdates"
      value: "no"
  when: clamav_offlinedb
  tags:
    - clamav

- name: clamav - update signatures
  ansible.builtin.service:
    name: clamav-freshclam
    state: restarted
  tags:
    - clamav
