- name: installing mail utilities
  ansible.builtin.apt:
    pkg:
      - mailutils
    state: present
    update_cache: yes

- name: shell - set MAIL variable for all users
  ansible.builtin.lineinfile:
    path: /etc/profile.d/mail.sh
    line: "export MAIL=$HOME/Maildir/"
    state: present
    create: yes
    owner: root
    group: root
    mode: 0644

- name: system - create mail forwarding from root to major administrative user
  ansible.builtin.lineinfile:
    path: /root/.forward
    create: yes
    mode: 640
    owner: root
    group: root
    line: "sysadmin@localhost"
    state: present
