- name: preparing
  ansible.builtin.import_tasks: prepare.yml
  tags:
    - prepare

- name: updater config
  ansible.builtin.import_tasks: updates.yml
  tags:
   - volumes

- name: preparing drives
  ansible.builtin.import_tasks: volumes.yml
  tags:
   - volumes

- name: snapd
  ansible.builtin.import_tasks: snapd.yml
  # tags:
    # - snapd

- name: software
  ansible.builtin.import_tasks: software.yml
  tags:
    - software

- name: networking
  ansible.builtin.import_tasks: network.yml
  tags:
    - network

- name: users
  ansible.builtin.import_tasks: users.yml
  tags:
    - users

- name: mailing
  ansible.builtin.import_tasks: mailing.yml
  tags:
    - mailing

- name: run external roles
  ansible.builtin.import_tasks: ext_roles.yml
  tags:
    - ext_roles

- name: misc system configurations
  ansible.builtin.import_tasks: system.yml
  tags:
    - system

- name: sudo
  ansible.builtin.import_tasks: sudo.yml
  tags:
    - sudo

- name: telemetry
  ansible.builtin.import_tasks: telemetry.yml
  tags:
    - telemetry

- name: time
  ansible.builtin.import_tasks: time.yml
  tags:
    - ntp

- name: kernel
  ansible.builtin.import_tasks: kernel.yml
  tags:
    - kernel

- name: restrictive logins
  ansible.builtin.import_tasks: logins.yml
  tags:
    - logins

- name: System scanners
  ansible.builtin.import_tasks: scanners.yml
  tags:
    - scanners



