- name: restrict playbook for debian based distributions
  block:
    - name: "End play"
      ansible.builtin.debug:
        msg: "Target system isn't debian based ... exit"
    - meta: end_play
  when: ansible_facts['os_family'] != "Debian"

- name: init variable os_type
  ansible.builtin.set_fact:
    os_type: ""

- name: get ubuntu distribution type
  block:
    - name: looking for desktop installation
      ansible.builtin.shell: apt list --installed |grep gnome-desktop
      register: search_desktop
      ignore_errors: true

    - name: set os-type - desktop
      ansible.builtin.set_fact:
        os_type: desktop
      when: search_desktop.stdout_lines is search("gnome-desktop")

    - name: set os-type - server
      ansible.builtin.set_fact:
        os_type: server
      when: search_desktop.stdout_lines is not search("gnome-desktop")

  when: ansible_distribution == 'Ubuntu'
