- name: AIDE - Check existent Database
  ansible.builtin.stat:
    path: /var/lib/aide/aide.db
  register: aide_db
  when: aide_db_build or aide_db_renew
  tags:
    - aide

- name: AIDE - Build and Test Database
  ansible.builtin.command: /usr/sbin/aideinit -y -f
  when: ( aide_db_build or aide_db_renew ) and not aide_db.stat.exists 
  tags:
    - aide

- name: AIDE - Stage Database
  ansible.builtin.copy:
    src: /var/lib/aide/aide.db.new
    dest: /var/lib/aide/aide.db
    backup: true
    remote_src: true
  when: ( aide_db_build or aide_db_renew ) and not aide_db.stat.exists 
  tags:
    - aide

- name: AIDE - remove duplicated database
  ansible.builtin.file:
    path: /var/lib/aide/aide.db.new
    state: absent
  tags:
    - aide