- name: snapd - get list of installed snaps
  ansible.builtin.command:
    cmd: "snap list"
  register: installed_snaps
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version >= "24.04"
  tags: snapd

- name: snapd - uninstall all snaps
  ansible.builtin.command:
    cmd: "snap remove --purge {{ item }}"
  loop: "{{ installed_snaps }}"
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version >= "24.04"
  tags: snapd

- name: snapd - disable services
  ansible.builtin.systemd:
    name: snapd
    enabled: false
    state: stopped
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version >= "24.04"
  tags: snapd

- name : snapd - remove
  ansible.builtin.apt:
    name: snapd
    state: absent
    purge: true
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version >= "24.04"
  tags: snapd

- name: snapd - remove unused packages
  ansible.builtin.apt:
    autoclean: true
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version >= "24.04"
  tags: snapd