- name: snapd - get list of installed snap applications
  ansible.builtin.shell: |
    snap list | grep -v 'core22\|snapd \|bare\|snap-store' | tail -n+2 | cut -d' ' -f1
  register: installed_snap_apps

- name: snapd - print installed snaps
  ansible.builtin.debug:
    msg: "Installed snaps: {{ installed_snap_apps.stdout_lines }}"

- name: snapd - uninstall all snap applications
  ansible.builtin.command:
    cmd: "snap remove --purge {{ item }}"
  loop: "{{ installed_snap_apps.stdout_lines }}"

- name: snapd - uninstall basic snaps
  ansible.builtin.command:
    cmd: "snap remove --purge {{ item }}"
  loop:
    - core22
    - bare
    - snapd

- name: snapd - disable services
  ansible.builtin.systemd:
    name: snapd
    enabled: false
    state: stopped

- name: snapd - remove
  ansible.builtin.apt:
    name: snapd
    state: absent
    purge: true

- name: snapd - remove unused packages
  ansible.builtin.apt:
    autoclean: true

- name: prevent snapd from being reinstalled
  ansible.builtin.copy:
    dest: /etc/apt/preferences.d/nosnap.pref
    src: nosnap.pref