- name: popularity - remove cronjob
  ansible.builtin.file:
    path: /etc/cron.d/popularity-contest
    state: absent

- name: popularity - remove daily cronjob
  ansible.builtin.file:
    path: /etc/cron.daily/popularity-contest
    state: absent
