- name: set ntp source
  ansible.builtin.lineinfile:
    path: "/etc/systemd/timesyncd.conf"
    regexp: '^#\s*NTP.*$'
    line: "NTP={{ ntp_source }}"
    backrefs: yes
    state: present

- name: restart ntp client
  ansible.builtin.service:
    name: systemd-timesyncd
    state: restarted

- name: set timezone
  ansible.builtin.command:
    cmd: timedatectl set-timezone Europe/Berlin