- name: auto-upgrades - disable automatic updates/lookups
  copy:
    src: 20auto-upgrades
    dest: /etc/apt/apt.conf.d/
    force: yes
    owner: root
    group: root
    mode: 0644

- name: remove unattended-upgrades
  apt:
    name: unattended-upgrades
    purge: yes
    autoremove: yes

- name: disable daily upgrade timer
  systemd:
    name: apt-daily-upgrade.timer
    state: stopped

- name: apt - disable daily upgrade service
  systemd:
    name: apt-daily-upgrade.service
    enabled: no
    masked: yes

- name: apt - disable daily timer
  systemd:
    name: apt-daily.timer
    state: stopped

- name: apt - disable daily service
  systemd:
    name: apt-daily.service
    enabled: no
    masked: yes
