# create new password hashes before runing this task

- name: load users
  include_vars: users.yml
  tags:
    - users

- name: change root password
  user:
    name: "root"
    update_password: always
    password: "{{ root_pwd }}"
  when: set_root_password
  tags:
    - users

- name: keep access to home directories more restrictive
  shell: chmod -R o-rwx /home/* /root/
  tags:
    - users
