# create new password hashes before runing this task
- name: change root password
  ansible.builtin.user:
    name: "root"
    update_password: always
    password: "{{ rootPwdSHA512 }}"
  when: set_root_password

- name: keep access to home directories more restrictive
  ansible.builtin.shell: chmod -R o-rwx /home/* /root/
