- name: reboot system
  ansible.builtin.include_tasks: reboot.yml

- name: clear caches
  ansible.builtin.include_tasks: clear_caches.yml

- name: dconf update
  ansible.builtin.include_tasks: dconf_update.yml
